# Generated by Django 4.2.7 on 2025-04-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0003_mentorados_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('G', 'Gestão'), ('M', 'Marketing'), ('RH', 'Recursos Humanos'), ('I', 'Impostos')], max_length=2)),
                ('descricao', models.TextField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.horarios')),
                ('mentorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.mentorados')),
            ],
        ),
    ]
